homeassistant:
  name: Översikt
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml
  packages: !include_dir_named extraconfig/packages


http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ip_ban_enabled: True
  login_attempts_threshold: 5


#panel_custom:
#  - name: floorplan
#    sidebar_title: Floorplan
#    sidebar_icon: mdi:home
#    url_path: floorplan
#    config: !include extraconfig/standalonefiles/floorplan.yaml

updater:
  include_used_components: true


ffmpeg:
  ffmpeg_bin: /usr/bin/avconv

influxdb:
  host: hem.gammelgravlingen.com
  username: !secret influx_user
  password: !secret influx_pw
  include:
    entities:
      - sensor.flower_1_temperature
  tags:
    instance: prod
    source: home


frontend:
  javascript_version: latest

discovery:
sun:
ios:
config:

logger: !include extraconfig/standalonefiles/logger.yaml

group: !include_dir_merge_named extraconfig/groups
#input_select: !include_dir_merge_named extraconfig/input_select
shell_command: !include_dir_merge_named extraconfig/shell_command
script: !include_dir_merge_named extraconfig/scripts

sensor: !include_dir_merge_list extraconfig/sensors

cloud: !include extraconfig/standalonefiles/cloud.yaml
google: !include extraconfig/standalonefiles/googlecalendar.yaml
media_player: !include extraconfig/standalonefiles/media_player.yaml
panel_iframe: !include extraconfig/standalonefiles/panel_iframe.yaml
switch: !include extraconfig/standalonefiles/switch.yaml
tts: !include extraconfig/standalonefiles/tts.yaml
zone: !include extraconfig/standalonefiles/zones.yaml
zwave: !include extraconfig/standalonefiles/zwave.yaml
