homeassistant:
  customize:
    script.wake_up:
      alexa_name: "Top of the morning"
      alexa_description: "Script to wake up"


automation:
  - action:
    - service: script.wake_up
    alias: Misc | Wake up in the morning
    id: '1495718802448'
    trigger:
    - hours: 5
      minutes: 45
      platform: time
      seconds: 0
    condition:
    - condition: and
      conditions:
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - condition: state
        entity_id: device_tracker.e9bdccf176d84a46b89bd9f4d8334c0a
        state: hemma
      - condition: state
        entity_id: input_boolean.arm_wakeup_alarm
        state: 'on'

script:
  wake_up:
      alias: "Dags att vakna"
      sequence:
        - alias: Group players just in case
          service: homeassistant.turn_on
          data:
            entity_id:
              - script.sonos_group_players

        - alias: Start low
          service: light.turn_on
          data:
            entity_id: light.sovrumstak
            brightness: 0

        - alias: Gradually on
          service: light.turn_on
          data:
            entity_id: light.sovrumstak
            brightness: 255
            transition: 900

        - alias: Living room gradually on
          service: light.turn_on
          data:
            entity_id: group.vardagsrum_tak
            brightness: 255
            transition: 900

        - alias: Set volume
          service: script.media_player_set_volume
          data_template:
            where: "living_room"
            volume_level: "0.12"

        - alias: Set volume
          service: script.media_player_set_volume
          data_template:
            where: "bathroom"
            volume_level: "0.1"

        - alias: Start radio
          service: script.media_player_select_source_play
          data_template:
            where: "living_room"
            select_source: "BBC Radio 4"

        - alias: Start kitchen lights
          service: light.turn_on
          data:
            entity_id: light.kokslampa
            brightness: 200

        - alias: Start hallway lights
          service: light.turn_on
          data:
            entity_id: light.hall_1, light.hall_2
            brightness: 254

        - alias: Start other
          service: homeassistant.turn_on
          data:
            entity_id:
              - switch.garderob
