homeassistant:
  customize:
    light.laslampa:
      alexa_name: "Reading lamp"
      alexa_description: "Reading lamp in the living room"
    light.kokslampa:
      alexa_name: "Kitchen light"
      alexa_description: "Rooftop light in kitchen"
    light.sovrum:
      alexa_name: "Bedroom light"
      alexa_description: "Rooftop light in bedroom"
    light.vardagsrum:
      alexa_name: "Living room"
      alexa_description: "Rooftop light in living room"
    light.hall:
      icon: mdi:ceiling-light
      alexa_name: "Hallway"
      alexa_description: "Rooftop light in hallway"
    light.vardagsrumstak_1:
      hidden: true
    light.vardagsrumstak_2:
      hidden: true
    light.vardagsrumstak_3:
      hidden: true
    scene.all_lights_off:
      alexa_name: "Enter night mode"
      alexa_description: "Shut of all lights"
    scene.ceiling_low:
      homebridge_visible: true
      homebridge_name: "Lampor lågt"
    scene.ceiling_mid:
      homebridge_visible: true
      homebridge_name: "Lampor medel"
    scene.ceiling_max:
      homebridge_visible: true
      homebridge_name: "Lampor högt"


light:
  - platform: tradfri
    host: 192.168.0.129
  - platform: hue
    host: 192.168.0.189


automation:
  - action:
    - service: script.a_walk_in_the_night
    hide_entity: True
    alias: Misc | Turn on light at night
    id: '1495643723115'
    trigger:
    - entity_id: binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor
      platform: state
      to: 'on'
    condition:
    - condition: and
      conditions:
      - after: 00:00:00
        before: 07:00:00
        condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      - condition: state
        entity_id: input_select.arm_debug
        state: Av

scene:
  - name: Ceiling low
    entities:
      group.hall_taklampa:
        state: on
        brightness: 1
      group.vardagsrum_tak:
        state: on
        brightness: 1
      light.kokslampa:
        state: on
        brightness: 1
      light.sovrumstak:
        state: on
        brightness: 1


  - name: Ceiling mid
    entities:
      group.hall_taklampa:
        state: on
        brightness: 100
      group.vardagsrum_tak:
        state: on
        brightness: 100
      light.kokslampa:
        state: on
        brightness: 100
      light.sovrumstak:
        brightness: 100
        state: on

  - name: Ceiling max
    entities:
      light.hall:
        state: on
      group.vardagsrum_tak:
        state: on
        brightness: 254
      light.kokslampa:
        state: on
        brightness: 254
      light.sovrumstak:
        state: on
        brightness: 20

  - name: All lights off
    entities:
      group.all_lights:
        state: off
      switch.garderob:
        state: off

  - name: Ceiling TV
    entities:
      group.hall_taklampa:
        state: on
        brightness: 100
      group.vardagsrum_tak:
        state: on
        brightness: 90
      light.kokslampa:
        state: off
      light.sovrumstak:
        state: off

script:
  a_walk_in_the_night:
      alias: "Dags att vakna"
      sequence:
        - alias: Start lights
          service: light.turn_on
          data:
            entity_id: light.laslampa
            brightness: 1
            rgb_color: [74, 65, 138]

        - delay:
            minutes: 5

        - alias: Start lights
          service: light.turn_off
          data:
            entity_id: light.laslampa
