homeassistant:
  customize:
    light.laslampa:
      alexa_name: "Reading lamp"
      alexa_description: "Reading lamp in the living room"
    light.kokslampa:
      alexa_name: "Kitchen light"
      alexa_description: "Rooftop light in kitchen"
    light.sovrum:
      alexa_name: "Bedroom light"
      alexa_description: "Rooftop light in bedroom"
    light.vardagsrum:
      alexa_name: "Living room"
      alexa_description: "Rooftop light in living room"
    light.vardagsrumstak_1:
      hidden: true
    light.vardagsrumstak_2:
      hidden: true
    light.vardagsrumstak_3:
      hidden: true
    light.hall:
      icon: mdi:ceiling-light
      alexa_name: "Hallway"
      alexa_description: "Rooftop light in hallway"


light:
  - platform: tradfri
    host: 192.168.0.129
  - platform: hue
    host: 192.168.0.189


automation:
  - action:
    - service: script.a_walk_in_the_night
    hide_entity: True
    alias: Misc | Turn on light at night
    id: '1495643723115'
    trigger:
    - entity_id: binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor
      platform: state
      to: 'on'
    condition:
    - condition: and
      conditions:
      - after: 00:00:00
        before: 07:00:00
        condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      - condition: state
        entity_id: input_select.arm_debug
        state: Av

scene:
  - name: Ceiling low
    entities:
      group.hall_taklampa:
        state: on
        brightness: 1
      group.vardagsrum_tak:
        state: on
        brightness: 1
      light.kokslampa:
        state: on
        brightness: 1
      light.sovrumstak:
        state: on
        brightness: 1


  - name: Ceiling mid
    entities:
      group.hall_taklampa:
        state: on
        brightness: 100
      group.vardagsrum_tak:
        state: on
        brightness: 100
      light.kokslampa:
        state: on
        brightness: 100
      light.sovrumstak:
        brightness: 100
        state: on

  - name: Ceiling max
    entities:
      group.hall_taklampa:
        state: on
        brightness: 254
      group.vardagsrum_tak:
        state: on
        brightness: 165
      light.kokslampa:
        state: on
        brightness: 254
      light.sovrumstak:
        state: on
        brightness: 254

  - name: All lights off
    entities:
      group.all_lights:
        state: off
      switch.garderob:
        state: off
      switch.koksbank:
        state: off
      switch.sovrum:
        state: off

  - name: Ceiling TV
    entities:
      group.hall_taklampa:
        state: on
        brightness: 100
      group.vardagsrum_tak:
        state: on
        brightness: 90
      light.kokslampa:
        state: off
      light.sovrumstak:
        state: off
