automation:
  - action:
    - service: script.arrive_home
    alias: Enter/exit | Home from work
    id: '1496517463812'
    trigger:
    - entity_id: device_tracker.e9bdccf176d84a46b89bd9f4d8334c0a
      platform: state
      to: 'hemma'
    condition:
    - condition: and
      conditions:
      - condition: time
        after: '15:00:00'
        before: '23:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - condition: state
        entity_id: input_select.arm_debug
        state: Av

  - action:
    - service: script.arrive_home_anytime
    alias: Enter/exit | Arrive home
    id: '1496517346021'
    trigger:
    - entity_id: device_tracker.e9bdccf176d84a46b89bd9f4d8334c0a
      platform: state
      to: 'hemma'
    condition:
      condition: state
      entity_id: input_select.arm_debug
      state: Av

  - action:
    - service: script.left_home
    alias: Enter/exit | Left home
    id: '1496517407855'
    trigger:
    - entity_id: device_tracker.e9bdccf176d84a46b89bd9f4d8334c0a
      platform: state
      to: 'not_home'


device_tracker:
  - platform: geofency


script:
  arrive_home_anytime:
    alias: Arrive home anytime
    sequence:
      - alias: Notify Patrik
        service: script.send_notification
        data_template:
          msg_title: 'Dobelnsgatan'
          msg_body: 'Nagon ar hemma'
      - alias: do stuff
        service: scene.turn_on
        entity_id: scene.ceiling_max

  arrive_home:
    alias: Arrive home
    sequence:
      - alias: Lights on
        service: homeassistant.turn_on
        data:
          entity_id:
          - switch.fibaro_system_fgwpe_wall_plug_switch

      - alias: Set volume
        service: script.media_player_set_volume
        data_template:
          where: "living_room"
          volume_level: "0.14"

      - alias: Set volume
        service: script.media_player_set_volume
        data_template:
          where: "bathroom"
          volume_level: "0.12"

      - alias: Start radio
        service: script.media_player_select_source_play
        data_template:
          where: "living_room"
          select_source: "Coffee Table Jazz"

      - alias: Start playlist
        service: shell_command.sonos_playlist_homefromwork

      - delay:
          minutes: 45

      - alias: Wardrobe off again
        service: homeassistant.turn_off
        data:
          entity_id:
          - switch.fibaro_system_fgwpe_wall_plug_switch

  left_home:
    alias: Left home
    sequence:
      - alias: Lights off
        service: homeassistant.turn_off
        data:
          entity_id:
          - group.lights
          - group.taklampor

      - alias: Sonos off
        service: shell_command.sonos_control_pause

      - alias: Webcam on
        service: homeassistant.turn_on
        data:
          entity_id:
          - switch.webcam

      - alias: Notify Patrik
        service: script.send_notification
        data_template:
          msg_title: 'Dobelnsgatan'
          msg_body: 'Ingen ar hemma'
