automation:
  - action:
    - service: script.sonos_stereo_on
    alias: Sonos | Vardagsrum | Start stereo
    id: '1496478237477'
    trigger:
    - entity_id: media_player.vardagsrum_musik
      platform: state
      to: playing

  - action:
    - service: script.sonos_stereo_off
    alias: Sonos | Vardagsrum | Stereo off (idle)
    id: '1496478400400'
    trigger:
    - entity_id: media_player.vardagsrum_musik
      platform: state
      to: idle

  - action:
    - service: script.sonos_stereo_off
    alias: Sonos | Vardagsrum | Stereo off (pause)
    id: '1496478447779'
    trigger:
    - entity_id: media_player.vardagsrum_musik
      platform: state
      to: paused

  - action:
    - service: shell_command.sonos_control_shuffle_off
    - service: shell_command.sonos_volume_8
    - service_template: 'shell_command.sonos_favorite_{{states.input_select.sonos_favorites.state.lower().replace("
        ", "").replace("-", "")}}

        '
    alias: Sonos | Play favorite
    id: '1496478661322'
    trigger:
    - entity_id: input_select.sonos_favorites
      platform: state

  - action:
    - service: shell_command.sonos_control_shuffle_off
    - service: shell_command.sonos_volume_8
    - service_template: 'shell_command.sonos_playlist_{{states.input_select.sonos_playlist.state.lower().replace("
        ", "").replace("-", "")}}

        '
    alias: Sonos | Play playlist
    id: '1496478802292'
    trigger:
    - entity_id: input_select.sonos_playlist
      platform: state

shell_command:
# SONOS MISC
  sonos_leave_main_group: '/usr/bin/curl -X GET http://192.168.0.140:5005/{{where}}/leave' # works better than built-in

# SONOS: COMFORTABLE VOLUMES
  sonos_volume_8: '/usr/bin/curl -X GET http://192.168.0.140:5005/vardagsrum%20musik/volume/8'
  sonos_volume_18: '/usr/bin/curl -X GET http://192.168.0.140:5005/vardagsrum%20musik/volume/18'

  sonos_volume_low: '/usr/bin/curl -X GET http://192.168.0.140:5005/vardagsrum%20musik/volume/30'
  sonos_volume_high: '/usr/bin/curl -X GET http://192.168.0.140:5005/vardagsrum%20musik/volume/50'

  sonos_badrum_volume_low: '/usr/bin/curl -X GET http://192.168.0.140:5005/badrum/volume/10'
  sonos_volume_custom: '/usr/bin/curl -X GET http://192.168.0.140:5005/vardagsrum%20musik/volume/'


# SONOS: BASIC COMMANDS COMMAND
  sonos_control_pause: /usr/bin/curl -X GET http://192.168.0.140:5005/vardagsrum%20musik/pause
  sonos_control_shuffle_on: /usr/bin/curl -X GET http://192.168.0.140:5005/vardagsrum%20musik/shuffle/on
  sonos_control_shuffle_off: /usr/bin/curl -X GET http://192.168.0.140:5005/vardagsrum%20musik/shuffle/off
  sonos_control_next: /usr/bin/curl -X GET http://192.168.0.140:5005/vardagsrum%20musik/next
